version: "2"

services:
  vote_blue:
    image: ${DTR}/vote_vote:${ENV}-${BUILD_NUMBER}
    command: python app.py
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    image: ${DTR}/vote_result:${ENV}-${BUILD_NUMBER}
    command: nodemon --debug server.js
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  worker:
    image: ${DTR}/vote_worker:${ENV}-${BUILD_NUMBER}
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis-${BUILD_NUMBER}
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    container_name: db-${BUILD_NUMBER}
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

