apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: vote-blue
  name: vote-blue
spec:
  type: NodePort
  ports:
  - name: "5000"
    port: 5000
    targetPort: 80
    nodePort: 30001
  selector:
    io.kompose.service: vote-blue
status:
  loadBalancer: {}
